### ISSUE TITLE
Google Apps Login?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-web-interface#1087]
Hi,

Is it possible to add Google Apps Login support? We are hosting all our business mail with Google and would like one login system :)

**Comment by kroepke** [comment]
I don't believe that oauth works without setting a specific redirect url for google.
Essentially it would require you to register your own graylog instance as a google app, which I can't believe users really want to do.

Since graylog is hosted on premise, I see no way of doing this, unfortunately (same goes for any other oauth provider).

**Comment by edmundoa** [comment]
Duplicate of #730
