### ISSUE TITLE
Adding alert to streams is inconsistent 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1183]
using `graylog-web-interface-1.1.0-SNAPSHOT-20150323175628.tgz`

When configuring a new alert condition, a user can choose between two conditions. When configuring new alert destination a user has also two choices in the dropdown menu plus a placeholder saying "new callback type" which is confusing. The placeholder should either be added to the new alert conditions or removed. Removing seems more reasonable.

**Comment by kroepke** [comment]
see if this makes sense to change in 1.1.0 otherwise move it out

**Comment by dennisoelkers** [comment]
Will do it the other way round and add placeholder to other dropdown as well.

**Comment by bernd** [comment]
I disagree with adding a placeholder to the other drop downs. I do not see
the purpose and it forces the user to do more clicks.

**Comment by edmundoa** [comment]
I am not a big fan of placeholders in select fields unless it's not clear what you have to select (e.g no titles or labels). Also, not using placeholders when the select has two or three options reduces the amount of clicks users will have to do, as the default option will be good in is quite good imo, as the default option will be good for a good percent of situations. Therefore, I would remove those placeholders, keeping the consistency we had so far, and only use them when they are needed.

Having said that, I should have caught this inconsistency while merging the PR and raise the topic then, sorry about that.

**Comment by dennisoelkers** [comment]
The point that removing the placeholder reduces the number of clicks is not valid, because the lists we are working on are populated dynamically and so the selected option is gonna be "random" (the first option returned by the server) or the option that comes first when sorted lexicographically. For both options it is _not_ the option that the majority of users would pick. For most of the variables there is no "default option" which we can deduce to be used in most of the cases, so highlighting an option this way is arbitrary and misleading.

Besides that, it's not that we are consistent regarding this right now. It's mixed placeholder/no placeholder at the moment.

**Comment by edmundoa** [comment]
I still think the number of clicks is a valid point. Even if the default selection is not a good one, with three options to choose from we may be able to save 10-15% of clicks.

Regarding consistency, I think _none_ of the select inputs had a placeholder until we started reworking the UI of outputs and streams, so there will be still less changes to do undoing them. It will also be harder to add placeholders on those views that still use play templates and jQuery.

Anyway, is there any good reason you want to have the placeholders? Maybe I am just missing something :)

**Comment by dennisoelkers** [comment]
Regarding your argument of saving 10-15% of clicks: Having only three options is not the norm in our application. We have selects with far more options. Still, I agree that we are saving a number of clicks, although the number is varying much. Even if we have only three options, we wouldn't save 1/3 of clicks if the option that is selected by default is a seldom used one. Thing is, if we want to have a reasonable sorting, preselection of the choice is not related to its usefulness at all. If we want to be precise, we are implicitly defining a default that just isn't one.
If we have a really small number of choices where a default selection could save clicks, a dropdown box is probably the wrong element to use and a radio button is better, as the user sees all available options at the same time.

From my POV, we could use the screen estate of the selected default of the dropdown to display helpful text in a place that is most certainly read. Other than that, it makes clear that this option _needs_ to be selected and there is _no default_ for it, which can help users to navigate through the form instead of generating the idea that they might just leave this alone.

**Comment by bernd** [comment]
This seems to be fixed in Graylog 2.0.
