### ISSUE TITLE
Delete local input is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-web-interface#1258]
When deleting a local input on `graylog-web-interface-1.1.0-SNAPSHOT-20150505130524.tgz` I receive the error message attached.

![bildschirmfoto 2015-05-05 um 15 59 55](https://cloud.githubusercontent.com/assets/6331205/7474620/cb6ac308-f342-11e4-8df6-ab5acccbf8e3.png)

**Comment by joschi** [comment]
Is GET really the proper HTTP method for deleting an input? It's changing state and it's not idempotent.
Sounds more like the UI action had been broken (which should use DELETE ideally or POST).

**Comment by bernd** [comment]
No, it's not the proper HTTP method. This has been broken by the re-design of the input page.

We use GET calls for deletion in other places as well and since this is not a public API our users use, I just took the easy route and added a GET route. I think we currently have more important work that doing a yak shave on this. :confused:

**Comment by kroepke** [comment]
I agree to all points, and also keep in mind that this API is not designed to be RESTful. Additionally hopefully most of the web interface controllers will go away, so I wouldn't spend too much time on issues like these.
If it was in the server, I would vehemently agree :)
