### ISSUE TITLE
gl2_source_collector fields are shown in sidebar

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#1290]
They should be excluded, like the other source_input fields etc

**Comment by bernd** [comment]
Hmm, `gl2_source_node` and `gl2_source_input` are actually shown in the sidebar as well. (also in 1.0)

Is that correct or not? /cc @kroepke @edmundoa

**Comment by kroepke** [comment]
Personally I have no problem showing them, because you can also search in them.
You can also use them to create stream alerts and stream rules, so they are useful, even though they are difficult to use because usually you don't get to see the correct values.

If the search had support for aliasing the values, I would hide agree to hide them, but in this case it would be better to group them as "system fields".

My vote is to simply show them.

**Comment by bernd** [comment]
They are currently shown in the sidebar but not in the message details because they are filtered [in MessageResult.java](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-rest-client/src/main/java/org/graylog2/restclient/models/api/results/MessageResult.java#L41-L44).

So if we show them, we should also show them in the message details.

I am also agree to show them to be able to use them in filters.

**Comment by bernd** [comment]
Okay, I was confused. The fields are shown when clicking on "all fields" in the sidebar.

Until we have separate pages for collectors so we can create links to them, I will filter the fields out.

**Comment by bernd** [comment]
Fixed in Graylog2/graylog2-server@60d0f1d
