### ISSUE TITLE
Auto reload messages

### ISSUE THREAD

**Issue by schickling** [Graylog2/graylog2-web-interface#133]
I think it would be a huge improvement if there'd be an option to enable auto reloading for messages and the activity graph.
Perhaps an input field for the refresh interval would also be nice.

**Comment by tomahock** [comment]
+1 this is would be awesome

**Comment by nmarshall-cst** [comment]
+1

**Comment by jshearer** [comment]
This is a vital feature to me. +9999

**Comment by psteyn** [comment]
+1 this would be really useful to us.

**Comment by vladimir-lu-work** [comment]
Is this something where SSE would be helpful to implement, given that it's been around in HTML5 for a bit now?

+1

**Comment by lawre** [comment]
+1 here as well.  This is the *only* reason why we haven't ditched Splunk yet

**Comment by jthomas332** [comment]
+1 Would be a very valuable addition to the interface.

**Comment by teon** [comment]
+100 - i feel graylog is ok for looking at the past - but I want to use it to look at the log "present" state and without feature like tail -f it's not possible.

**Comment by nickamon** [comment]
Still no update?

**Comment by sam0737** [comment]
That's one single thing that Kibana is better than graylog.
Even dashboard chart could be refreshed, can we take another approach of putting the result table to the dashboard?  Instead of adding refresh ability on the "search" page.

**Comment by TravisCrist** [comment]
Is this issue ever going to be resolved? 

Its existed since 2013 and is a key feature for any logging framework in a live server environment.

**Comment by zexxon** [comment]
We have made several major improvements to the UI in the upcoming 1.1 release, which is one of the reasons we held off on implementing this feature. Will scope for the next maintenance/minor release and see if we can get it in post 1.1. It should be interesting to see how it performs vs. Kibana and Splunk since we are able to buffer log messages via the app server.

**Comment by TravisCrist** [comment]
That would be great to see this in the next release. One of our teams biggest complaints with using graylog is the inability to access live logs. If we can resolve that issue via a version update our users would be in great shape. 

Thanks!

**Comment by hernandesbsousa** [comment]
:+1:

**Comment by thenetexperts** [comment]
any update on this one?

**Comment by shakalandy** [comment]
Some more beer for this one ;)

**Comment by HerrmannHinz** [comment]
+1
where should i donate?

**Comment by jshearer** [comment]
Jeez I've been following this ticket for a loooong time. Still nothing. D'oh

**Comment by tomahock** [comment]
It was supposed to be in 1.2 version:
https://twitter.com/_lennart/status/593195512414613504

**Comment by lennartkoopmann** [comment]
@tomahock it is on the roadmap for 1.2 but we cannot guarantee yet that it will definitely make it in.

We understand that this is a frequently requested feature but we want to get the implementation right and not rush this. There are many ways to shoot your own foot with this so it make take a bit more time.

**Comment by tpowell-rms** [comment]
+1  :-)
... and a 1,000,000 Internet points to Graylog when they get this in.

![Make it Rain](http://media.giphy.com/media/ZPFQVis9WAAcE/giphy.gif)

**Comment by tomahock** [comment]
@lennartkoopmann we love feedback :D

**Comment by brandongalbraith** [comment]
@lennartkoopmann Thank you for the update!!

**Comment by hwinkel** [comment]
+1

**Comment by umatomba** [comment]
+1 )))

**Comment by Brennwert** [comment]
+1

**Comment by bymodude** [comment]
+1

I just spent a day getting log messages into Gelf Format and into the Graylog2 server, due to this issue and seeing that its been open for 2 years (and therefore its clearly not a priority for the graylog2 team?), I am probably just going to throw that away and go Kibana/Splunk etc instead. 

I don't know what peoples use cases are, but for me this is such a basic thing that I just assumed this would of course be possible.

Seriously I am certain this costs you hundreds if not thousands of potential users. I seldomly provide feedback like this when features are missing, normally I just move on, I guess others came across this glaring omission and just moved on similarly.

**Comment by dedene** [comment]
This is also one of the only reasons we are not using Graylog (yet).

+1

**Comment by jshearer** [comment]
Yet again I would like to add my two cents here. Add this already

**Comment by sv72** [comment]
Was very enthousiastic at first when I just installed GrayLog as a possible replacement of Splunk. That was until I found out that there's no (near) realtime view. This is what we use a lot in our current Splunk setup for debugging issues on our webshops. 

Seeing that this feature request already exists for 2,5 years I don't think I'm going to wait for this.
Too bad though, I think the concept of Graylog is pretty great.

**Comment by brandongalbraith** [comment]
Hey all! I'm not affiliated with Graylog at all, but this is pretty disheartening. Not that the feature isn't here yet, but because of every +1 or complaint here without a pull request.

If you're signaling interest for a feature, awesome. But complaining that an open source project that you're providing no contribution to should prioritize a feature because _you want it_? That is not what open source is about.

Graylog is pretty damn incredible for an open source project. And it is **far better** than alternatives (ie Splunk) considering the cost. I've someone from Graylog reads this, feel free to lock this issue and move on.

**Comment by let4be** [comment]
deal breaker for my use case...
An update?

**Comment by lennartkoopmann** [comment]
Everyone, it looks like we will have this in Graylog v2.0:

![livetail](https://cloud.githubusercontent.com/assets/35022/12962109/91b8c840-d009-11e5-9d86-3b8d79a943cd.gif)

**Comment by dedene** [comment]
@lennartkoopmann Awesome! :+1:

**Comment by dennisoelkers** [comment]
Implemented in https://github.com/Graylog2/graylog2-server/pull/1783.
