### ISSUE TITLE
Export search result gets error

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/graylog2-web-interface#1474]
with new graylog webinterface (v1-1-2, also v1-1-1)no csv export of search result is possible. i get this error message: 
The response to this request is chunked and hence requires HTTP 1.1 to be sent, but this is a HTTP 1.0 request.
Browser: Firefox ESR 31.4.0

**Comment by kroepke** [comment]
Are you using a proxy in between?
I'm not aware of any browser that does not support HTTP 1.1, and since streaming CSV results can only be done efficiently, it needs HTTP 1.1.

ESR 31 definitely supports 1.1, I have just tested with 31.7 on Mac and it correctly does the request.

Please verify that your company's proxy settings support HTTP 1.1.
I'll close this issue, please reopen it if your environment is correctly set up and we will investigate more.

Thank you :)

**Comment by plt-sun** [comment]
i started with graylog my first installation last week from OVA image, version 1.0.2. With this version it was possible to export searches to CSV Files. we use a proxy with authentication to connect to internet, however graylog server is not running behind the proxy but in our network segment. we don't connect to graylog server through our proxy. on tuesday a updated (v1.1.1) this graylog installation from this source: https://packages.graylog2.org/releases/graylog2-omnibus/ubuntu/graylog_latest.deb and yesterday i want t to export some searches to csv, but i get the described error. so, today i installed the newest, latest debfile (v1.1.2), but in won't work. 
i checked proxy http setiings in firefox: network.http.proxy.version = 1.1
so, i have no idea what is going wrong

**Comment by plt-sun** [comment]
thanks for reopen https://github.com/Graylog2/graylog2-web-interface/issues/1474, but i can't do this myself.

**Comment by kroepke** [comment]
This seems to be a problem with the appliances. We will see if we can update them.

It is running an nginx instance which seems to have a problem with the configuration.

**Comment by mariussturm** [comment]
@plt-sun could you please update your appliance: https://github.com/Graylog2/graylog2-images/tree/master/ova#upgrade-graylog
Your problem should be fixed now.

**Comment by plt-sun** [comment]
Yep, problem solved. csv export is now working

**Comment by ericlevin** [comment]
is there a workaround that does not involve upgrading the appliances?  Is there an nginx config change I can make?

**Comment by mariussturm** [comment]
@ericlevin this is over a year old, your should seriously consider an update. I think this was the fix for the csv export: https://github.com/Graylog2/omnibus-graylog2/commit/87e1661445aa7b7249cdc6ad19ea4964abf7ba14 Keep in mind that a manual change of the Nginx config will be reset by running graylog-ctl reconfigure.

**Comment by ericlevin** [comment]
We have a 9 node cluster.  Upgrade is on the list.  Will get 'er done in early 2017...but this is a blocker for me today.

Thanks for the link.  Looking now.
