### ISSUE TITLE
Query generation in Web-Interface buggy?

### ISSUE THREAD

**Issue by SEAIT** [Graylog2/graylog2-web-interface#1544]
Hi,
We entered a search for a specific field, the search was successful. 
We entered another search pattern and received no result. Promis the Value is in the DB.
We looked at the Query source and noticed that the search value was buggy.
Here the samples:
This query was successful...D_msgid:%asa\-4\-*  ( Cisco Log Message ID )
This query failed:..................D_msgid:%ace\-4\-*  ( see attached image for query source)
This query was successful...D_msgid:%\ace\-4\-*            
This query failed...................D_msgid:%bcd\-4\-*           
This query was successful...D_msgid:%\bcd\-4\-*            
This query was successful...D_msgid:%zel\-4\-*            

Version is 1.1.5  also seen under 1.1.4
Any ideas?

![bcd_esc_b_success-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956130/2091012e-35f3-11e5-9b6f-0ad1f4f07c4c.png)
![zel_success-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956134/2094c246-35f3-11e5-9af3-fbf93389318f.png)
![bcd_failed-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956132/209380b6-35f3-11e5-825e-668b00e0b496.png)
![asa_success-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956129/208fa93c-35f3-11e5-8884-153f7f8d7ac7.png)
![ace_esc_a_success-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956131/20928cce-35f3-11e5-8129-bd489487b0ce.png)
![ace_failed-graylog - search](https://cloud.githubusercontent.com/assets/13554090/8956133/2093a29e-35f3-11e5-9a53-500b5beb5099.png)

**Comment by edmundoa** [comment]
Hi,

The issue you are experiencing is due to URL encoding, similar to the one described in #1523. At the moment, search requests are being sent as a GET parameter, meaning that they need to be encoded in URL format and then decoded in the server to get the actual query. There is apparently a problem encoding those percentage signs in your query, and that is generating a wrong query in the server.

As a workaround until we fix the issue, I suggest that you avoid using percentages in your queries, as Elasticsearch will ignore them anyway, as far as I know.
