### ISSUE TITLE
Unexpected behavior when uging rest_transport_uri by web-interface

### ISSUE THREAD

**Issue by SergeyBear** [Graylog2/graylog2-web-interface#1572]
I installed latest graylog2 1.1.6 with web behind nginx and got some issues with used uris.
Nginx proxying graylog.domain.com to http://127.0.0.1:9000 and api.graylog.domain.com to http://127.0.0.1:12900

For server I used:
rest_listen_uri = http://127.0.0.1:12900/
rest_transport_uri = https://api.graylog.domain.com:443/

Fnd for the web I used:
graylog2-server.uris="http://127.0.0.1:12900/"

Expected:
Web-interface communicates with server by using http://127.0.0.1:12900/ and all uris in the web-interface should be set to  https://graylog.domain.com/$uri (api browser, connection checking etc). For example, clicking System -> Nodes -> API Browser redirects to 'https://graylog.domain.com/api-browser'.

Got:
web communicates with server by using https://api.graylog.domain.com:12900/. So all requests goes not directly but through proxy which is not optimal. When clicking System -> Nodes -> API Browser web-browser redirects 'https://api.graylog.domain.com:443/api-browser' to 'https://api.graylog.domain.com/' and warning popup shows that I should use 'https://api.graylog.domain.com:443/' instead of 'https://api.graylog.domain.com/'.

So I think there are two problems:
1. When 'rest_transport_uri' specified without port, then port from 'rest_listen_uri' (eg. 12900) should not be added automatically.
2. Web-interface should communicate using 'graylog2-server.uris' and use 'rest_transport_uri' only for external links/buttons in web-interface (like /api-browser and such).

**Comment by jdelvecchio** [comment]
got exactly the same problem, any updates ?

**Comment by edmundoa** [comment]
No updates, this issue is quite old, and the Graylog web interface has changed a lot since the issue was created. In fact, I'm closing the ticket, as I think most of the problems should be gone by using a newer version.

Please update to Graylog 2.0 and follow the documentation to [configure the web interface](http://docs.graylog.org/en/latest/pages/configuring_webif.html). If you find any problems with that, please use one of our [support channels](https://www.graylog.org/community-support).
