### ISSUE TITLE
Add missing marketplace buttons

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-web-interface#1581]
In the current 1.2 branch, we have buttons to find more inputs and alarm callbacks on the upcoming Graylog marketplace. We should also add buttons to find outputs and content packs.

**Comment by lennartkoopmann** [comment]
Good catch! The outputs and content packs have links in their help texts already because there was no good way to crowd buttons in there without overloading the UI. 

I planned to integrate those buttons with a general UX overhaul of those two pages. For now less consistency compared to the other pages is a tradeoff for a cleaner functioning page.

**Comment by edmundoa** [comment]
Oh, I even missed those links while looking through it. Thank you for the info! :+1:
