### ISSUE TITLE
graylog-web-1.2.1 still creates unsupported diffe-hellman keys

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog2-web-interface#1616]
Hi there

If you configure graylog-web for HTTPS, it will auto-create a cert with a 768bit DH key. Firefox and Chrome refuse to talk to it (ERR_SSL_WEAK_SERVER_EPHEMERAL_DH_KEY)

I'd suggest increasing it to 1024bit - which everything is (currently) happy with

Obviously creating your own cert store and importing a "real" cert in fixes all of this - but your auto-create code basically doesn't work for "real" browsers, so I thought you should know :-)

Jason

**Comment by joschi** [comment]
Which version of Java are you running?

**Comment by jhaar** [comment]
Good question. It's the one that is current on CentOS-6 - java-1.7.0-openjdk-headless

I assume you're going to say that java-1.8 would have made 1024bit keys? My point was why not explicitly force it?

**Comment by joschi** [comment]
> I assume you're going to say that java-1.8 would have made 1024bit keys?

Yes, and the size would actually be configurable, so you could also use keys with 2048 bits. In general I'd recommend using a version of Java, which hasn't reached EOL.

> My point was why not explicitly force it?

Because SunJCE of Java 7 (the default JSSE provider) doesn't support configuring the key size. Of course you could install another JSSE provider which supports larger key sizes for the Diffie-Hellman parameters.

In a future version of Graylog we might use Java 8 as a baseline, but for Graylog 1.x we'd like to stay compatible with Java 7.
