### ISSUE TITLE
Chromium crashes after some hours using dashboard-functionality on a raspberry pi 

### ISSUE THREAD

**Issue by PatrickHuetter** [Graylog2/graylog2-web-interface#1632]
We are using some raspberry pi 2b to render the graylog dashboards on our monitoring screens.
This worked many months without problems. 

After upgrading to the new graylog-web-interface v1.1.6 (2e264c2) chromium crashes after some hours (mostly after 24 hours in use). This may be a memory problem within the web interface javascript.

**Comment by edmundoa** [comment]
Hi,

It's hard to tell where the problem is from here. The raspberry pi is quite constrained in memory and the issue could be related to different things. Could you please try to reproduce this issue in the latest Graylog version (1.2.2)?

If this also happens with the latest version, please reopen the issue and include more details about the dashboard (number of widgets, cache time, and so on), the raspberry configuration, and what applications are running on it. It would also be great if you could try using another browser, even if it's only to see the outcome of it.

Thank you!
