### ISSUE TITLE
Issue escaping colon from message field in quick values

### ISSUE THREAD

**Issue by jonathanrico** [Graylog2/graylog2-web-interface#1669]
If we have the following value in the message field "RuntimeError: No client token found" , getting a list of quick values returns values for no, client, token and found. This doesn't seem to happen with other fields.

**Comment by joschi** [comment]
@jonathanrico Graylog is using an index mapping which analyzes the following message fields: `message`, `full_message`, `source`.

Those message fields are being tokenized and analyzed by Elasticsearch/Lucene so that full text search is enabled on those fields. Other message fields are *not* analyzed by default.

**Comment by jonathanrico** [comment]
got it, thanks @joschi
