### ISSUE TITLE
Dashboard time controls

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-web-interface#650]
I would really love to be able to manipulate the time interval for an entire dashboard instead of trying to built different dashboard (ie. what's happening now, last day, last week, etc).

Mimicking the time controls already present for searches would make the interface coherent.

**Comment by bernd** [comment]
Already on the roadmap. Closing this one now.

**Comment by Uthpala08** [comment]
Hello , I would like to know the status of above request. We are also expecting the same :)

**Comment by chriscore** [comment]
Any plans for this still in the roadmap? It would be massively useful for us.

**Comment by colegatron** [comment]
Would be great at least to be able to export a dashboard as content pack and then import it twice in order to have it duplicated and have a dashboard for each timespan (last 24hours, last week, etc)

I can export a content pack as json file but can't import it without having to share it in the marketplace. For privacy reasons my dashboards can't be shared throug it.

**Comment by ilionic** [comment]
Is it still in the roadmap? Missing this feature after Kibana

**Comment by lennartkoopmann** [comment]
This is all coming in v3.0! Stay tuned.
